<?php
declare(strict_types=1);

namespace PersonDBSkeleton\Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Addresses
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Addresses extends EntityRepository {
}
