<?php
declare(strict_types=1);

namespace PersonDBSkeleton\Model\Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * People
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeopleRepository extends EntityRepository {
    use ArrayExceptionCommon;
    /**
     * @param string $name
     *
     * @return array
     */
    public function browseByName(string $name): array {
        $expr = new Expr();
        $query = $this->createQueryBuilder('p')
                      ->select('p')
                      ->where($expr->like('p.givenName', "'%:name%'"))
                      ->orWhere($expr->like('p.familyName', "'%:name%'"))
                      ->orWhere($expr->like('p.additionalName', "'%:name%'"))
                      ->setParameter('name', $name)
                      ->getQuery();
        return $query->getResult();
    }
}
