<?php

namespace PersonDBSkeleton\Model\Proxies\__CG__\PersonDBSkeleton\Model\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Addresses extends \PersonDBSkeleton\Model\Entities\Addresses implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'countryName', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'extendedAddress', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'locality', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'people', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'postOfficeBox', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'postalCode', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'region', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'streetAddress', 'createdAt', 'id'];
        }

        return ['__isInitialized__', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'countryName', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'extendedAddress', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'locality', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'people', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'postOfficeBox', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'postalCode', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'region', '' . "\0" . 'PersonDBSkeleton\\Model\\Entities\\Addresses' . "\0" . 'streetAddress', 'createdAt', 'id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Addresses $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addPerson(\PersonDBSkeleton\Model\Entities\PeopleAddresses $person): \PersonDBSkeleton\Model\Entities\Addresses
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerson', [$person]);

        return parent::addPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function deletePerson(\PersonDBSkeleton\Model\Entities\PeopleAddresses $person): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deletePerson', [$person]);

        return parent::deletePerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryName', []);

        return parent::getCountryName();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtendedAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtendedAddress', []);

        return parent::getExtendedAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocality(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocality', []);

        return parent::getLocality();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeople(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeople', []);

        return parent::getPeople();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostOfficeBox(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostOfficeBox', []);

        return parent::getPostOfficeBox();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', []);

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function getStreetAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreetAddress', []);

        return parent::getStreetAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountryName(string $value): \PersonDBSkeleton\Model\Entities\Addresses
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountryName', [$value]);

        return parent::setCountryName($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setExtendedAddress(string $value = NULL): \PersonDBSkeleton\Model\Entities\Addresses
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtendedAddress', [$value]);

        return parent::setExtendedAddress($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocality(string $value): \PersonDBSkeleton\Model\Entities\Addresses
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocality', [$value]);

        return parent::setLocality($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setPostOfficeBox(string $value = NULL): \PersonDBSkeleton\Model\Entities\Addresses
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostOfficeBox', [$value]);

        return parent::setPostOfficeBox($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode(string $value): \PersonDBSkeleton\Model\Entities\Addresses
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$value]);

        return parent::setPostalCode($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion(string $value = NULL): \PersonDBSkeleton\Model\Entities\Addresses
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', [$value]);

        return parent::setRegion($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setStreetAddress(string $value = NULL): \PersonDBSkeleton\Model\Entities\Addresses
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreetAddress', [$value]);

        return parent::setStreetAddress($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

}
